name: my-first-drupal10-app
recipe: drupal10
config:
  webroot: web
  php: '8.2'
  memory_limit: 4096M

services:
  appserver:
    overrides:
      environment:
        PHP_MEMORY_LIMIT: 4096M

  phpmyadmin:
    type: phpmyadmin
